'use client'

import { globalStyles } from '@/styles/global'
import './styles.css'

globalStyles()

export const metadata = {
  title: 'Ignite call',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  )
}
